# Generated by Django 5.2.4 on 2025-08-14 12:48

import django.db.models.deletion
import hotel.utils.path
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=hotel.utils.path.dynamic_upload_path)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('imageable_type', models.CharField(max_length=15)),
                ('imageable_id', models.UUIDField()),
                ('hotel', models.UUIDField(blank=True, db_index=True, null=True)),
                ('city', models.UUIDField(blank=True, db_index=True, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=15, null=True)),
                ('city_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=15)),
                ('description', models.TextField()),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.location')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=15, null=True)),
                ('description', models.TextField()),
                ('accessibility', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=4)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='LocalAttraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('accessibility', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], db_index=True, default='Free', max_length=4)),
                ('type', models.CharField(db_index=True, max_length=20)),
                ('availability', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.city')),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.location')),
            ],
        ),
        migrations.CreateModel(
            name='HotelAttraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_attractions', to='hotel.hotel')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attraction_hotels', to='hotel.localattraction')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('type', models.CharField(db_index=True, max_length=15)),
                ('room_no', models.IntegerField()),
                ('price_per_night', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(db_index=True, default=True)),
                ('number_of_beds', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=15)),
                ('description', models.TextField()),
                ('availability', models.BooleanField(default=True)),
                ('amenityable_type', models.CharField(default='Hotel', max_length=15)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='hotel.hotel')),
                ('amenityable_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_amenities', to='hotel.room')),
            ],
        ),
    ]
