# Generated by Django 5.2.4 on 2025-08-14 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_image_city_event_localattraction_hotelattraction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotel.city')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='hotel.hotel')),
            ],
        ),
    ]
