# Generated by Django 5.2.4 on 2025-08-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotelcities'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('latitude', 'longitude')},
        ),
    ]
