# Generated by Django 5.2.4 on 2025-08-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotel_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hotel', 'room_no')},
        ),
    ]
