# Generated by Django 5.2.4 on 2025-08-20 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_city_favorite_hotelhistoryonline_localattraction_and_more'),
        ('hotel', '0006_alter_room_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelcities',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='business.city'),
        ),
        migrations.RemoveField(
            model_name='localattraction',
            name='city',
        ),
        migrations.RemoveField(
            model_name='localattraction',
            name='location',
        ),
        migrations.AlterField(
            model_name='hotelattraction',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attraction_hotels', to='business.localattraction'),
        ),
        migrations.CreateModel(
            name='HotelHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_contact', models.CharField(max_length=50)),
                ('guest_nationality', models.CharField(max_length=100)),
                ('guest_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='histories', to='business.booking')),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='LocalAttraction',
        ),
    ]
