# Generated by Django 5.2.4 on 2025-08-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_hotelcities_city_remove_localattraction_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelCities',
        ),
    ]
