# Generated by Django 5.2.4 on 2025-08-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_delete_hotelcities'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city_in',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
