# Generated by Django 5.2.4 on 2025-09-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_location_city_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city_in',
        ),
    ]
