# Generated by Django 5.2.4 on 2025-09-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_remove_location_city_in'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelHistory',
        ),
    ]
