# Generated by Django 5.2.4 on 2025-08-20 13:49

import django.db.models.deletion
import hotel.utils.path
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('hotel', '0005_alter_hotel_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, max_length=25, null=True)),
                ('guest_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('guest_nationality', models.CharField(default='Ethiopian', max_length=15)),
                ('guest_gender', models.CharField(default='Male', verbose_name=[('Male', 'Male'), ('Female', 'Female')])),
                ('guest_id_image', models.ImageField(blank=True, null=True, upload_to=hotel.utils.path.user_id_image_upload_path)),
                ('receptionist', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_adults', models.IntegerField()),
                ('number_of_children', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('booking_source', models.CharField(choices=[('Online', 'Online'), ('In person', 'In person')], default='Online')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')])),
                ('payment', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to='hotel.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_bookings', to='hotel.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
