# Generated by Django 5.2.4 on 2025-08-20 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_hotelhistory_userhistory'),
        ('hotel', '0006_alter_room_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=15)),
                ('description', models.TextField()),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.location')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hotel', models.UUIDField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelHistoryOnline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.UUIDField()),
                ('booking_id', models.UUIDField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalAttraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('accessibility', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], db_index=True, default='Free', max_length=4)),
                ('type', models.CharField(db_index=True, max_length=20)),
                ('availability', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.city')),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.location')),
            ],
        ),
        migrations.DeleteModel(
            name='HotelHistory',
        ),
    ]
