# Generated by Django 5.2.4 on 2025-08-20 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_city_favorite_hotelhistoryonline_localattraction_and_more'),
        ('hotel', '0008_delete_hotelcities'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='business.city')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='hotel.hotel')),
            ],
        ),
    ]
