# Generated by Django 5.2.4 on 2025-09-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_hotelcities'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Online'), ('Cash', 'Cash'), ('Card', 'Card'), ('None', 'None')], default='None'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending'),
        ),
    ]
