# Generated by Django 5.2.4 on 2025-09-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_booking_payment_method_alter_booking_guest_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Checked_in', 'Checked In'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
