# Generated by Django 5.2.4 on 2025-09-04 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_booking_status_alter_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelhistoryonline',
            name='hotel',
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Checked_in', 'Checked in'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending'),
        ),
    ]
