# Generated by Django 5.2.4 on 2025-09-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_hotelhistoryonline_hotel_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelhistoryonline',
            old_name='booking_id',
            new_name='booking',
        ),
    ]
