# Generated by Django 5.2.4 on 2025-09-04 19:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_rename_booking_id_hotelhistoryonline_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.UUIDField()),
                ('hotel', models.UUIDField()),
                ('booking', models.UUIDField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('source', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='HotelHistoryOnline',
        ),
    ]
