# Generated by Django 5.2.4 on 2025-09-05 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_hotelhistory_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelhistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.booking'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.booking'),
        ),
    ]
